### ISSUE TITLE
Need support for AbortSignal in the fetch calls

### ISSUE THREAD

**Issue by pteigen** [jhannes/openapi-generator-typescript-fetch-api#12]
Hello. We use this generator for our main project at the moment. We find it useful and it generates good code that is easy to use.

Alltough we recently have run into an issue where it is needed to abort the fetch calls beeing generated. Currently there is no support for this.

I've noticed there is a branch that encorporates AbortController/AbortSignal in the calls to fetch. This would be perfect for our use.

On that note I would highly encourage that this branch is merged to main in the near future!

Thank you!

**Comment by jhannes** [comment]
Version 0.3.0 is now published with support for abort signals and other request parameters
