### ISSUE TITLE
Does this generator support for generating typescript enum 

### ISSUE THREAD

**Issue by MrEspiritu** [jhannes/openapi-generator-typescript-fetch-api#18]
Hi, 
Does the generator have some support for generating typescript enum such as it does with generating const toValues[]?

**Comment by jhannes** [comment]
Thanks for the question. I've seen a bit of information about bad properties of Typescript/JavaScript enums as so I've opted for string literals instead. Searching for "typescript enum drawbacks" will provide you with the reasoning behind this choice.
